# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.TextField(default='http://www.ssu.ac.kr/web/kor/plaza_d_01'),
            preserve_default=False,
        ),
    ]
