# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0002_auto_20171021_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='category',
            new_name='categories',
        ),
    ]
