# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0005_auto_20171021_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
