# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0008_auto_20171109_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hits',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
