# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0009_auto_20171109_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hits',
            name='hits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hits',
            name='notice_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hits',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
