# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0010_auto_20171116_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hits',
            name='hits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hits',
            name='notice_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='hits',
            field=models.PositiveIntegerField(),
        ),
    ]
