# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0011_auto_20171116_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='exponent',
            field=models.FloatField(default=0.0),
        ),
    ]
