# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawling', '0012_notice_exponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='initials',
            field=models.TextField(null=True),
        ),
    ]
