# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('hits', models.IntegerField()),
                ('owner', models.CharField(max_length=24)),
            ],
        ),
    ]
