# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('speech', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidentified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('speech_request', models.TextField()),
                ('speech_response', models.TextField(null=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
