# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_kakao', '0002_auto_20180101_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unidentified',
            new_name='Unknown',
        ),
    ]
